---
# Create a simpler EC2 instance

- name: Create a simple EC2 instance
  hosts: localhost
  connection: local
  tasks:
    - name: Provision new VM instance
      ec2:
        key_name: {{ key }}
        instance_tags: {Name: "{{ name }}"}
        group_id: "{{ security_group }}"
        image: "{{ image }}"
        wait: yes
        count: 1
        vpc_subnet_id: "{{ subnet }}"
        assign_public_ip: yes
        region: {{ region }}
      register: ec2
