---
# Create a simpler EC2 instance

- name: Create a simple EC2 instance
  hosts: localhost
  connection: local
  tasks:
    - name: Provision new VM instance
      ec2:
        key_name: mykeyaws
        instance_type: t2.micro
        instance_tags: {Name: "{{ name }}"}
        group: default
        image: "{{ image }}"
        wait: yes
        count: 1
        vpc_subnet_id: "{{ subnet }}"
        assign_public_ip: yes
        region: eu-central-1
      register: ec2
