---
# Create a simpler EC2 instance

- name: Create a simple EC2 instance
  hosts: localhost
  connection: local
  tasks:
    - name: Provision new VM instance
      ec2:
        key_name: {{ dialog_key }}
        instance_tags: {Name: "{{ dialog_name }}"}
        group_id: "{{ dialog_security_group }}"
        image: "{{ dialog_image }}"
        wait: yes
        count: 1
        vpc_subnet_id: "{{ dialog_subnet }}"
        assign_public_ip: yes
        region: {{ dialog_region }}
      register: ec2
