---
# Create a simpler EC2 instance

- name: Create a simple EC2 instance
  hosts: localhost
  connection: local
  tasks:
    - name: Provision new VM instance
      ec2:
        instance_tags: {Name: "{{ name }}"}
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet }}"
        instance_type: "{{ instanceType }}"
        image: "{{ image }}"
        group: "{{ groupName }}"
        assign_public_ip: yes
        key_name: "{{ key }}"
        wait: yes
        count: 1
      register: ec2
