---
# Create a simpler EC2 instance with service linking

- name: Create a simple EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False

  roles:
  - syncrou.manageiq-vmdb

  tasks:

    - name: Get a vmdb object
    manageiq_vmdb:
      href: "services/80"
    register: vmdb_object

    - name: Provision new VM instance
      ec2:
        instance_tags: {Name: "{{ name }}"}
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet }}"
        instance_type: "{{ instanceType }}"
        image: "{{ image }}"
        group: "{{ groupName }}"
        assign_public_ip: yes
        key_name: "{{ key }}"
        wait: yes
        count: 1
      register: ec2

    - name: Service Linking via an object
    manageiq_vmdb:
      vmdb: "{{ vmdb_object }}"
      action: add_provider_vms
      data:
        uid_ems:
          - "asdf1234"
        provider:
          id: "{{ provider_id }}"
